version: '3'

services:
  mongo:
    image: 'mongo'
    volumes:
      - 'mongo:/data'

  serverblog:
     build: './mongoserver'
     depends_on:
      - 'mongo'
     ports:
      - '3000:3000'

  blogin:
    build: '.'
    depends_on:
      - 'serverblog'
    ports:
      - '8081:8081'

volumes:
  mongo: {}